version: "3.9"

services:
  front:
    build:
      context: ./front_despacho
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    environment:
      - NODE_ENV=production
    depends_on:
      - ventas
      - despachos

  ventas:
    build:
      context: ./back-Ventas_SpringBoot/Springboot-API-REST
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=h2

  despachos:
    build:
      context: ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=h2
      - SERVER_PORT=8081
    depends_on:
      - ventas
