services:
  # --- BASE DE DATOS MYSQL LOCAL ---
  db-mysql:
    image: mysql:8.0
    container_name: db-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ev_devops
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  # --- MICROSERVICIO VENTAS ---
  ventas:
    build: 
      context: ./back-Ventas_SpringBoot/Springboot-API-REST
    container_name: back-ventas
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      db-mysql:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/ventas_db?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  # --- MICROSERVICIO DESPACHOS ---
  despachos:
    build: 
      context: ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
    container_name: back-despachos
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      db-mysql:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/despachos_db?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  # --- FRONTEND VITE ---
  front:
    build: 
      context: ./front_despacho
    container_name: front-despacho
    restart: always
    ports:
      - "4173:8080"
    depends_on:
      - ventas
      - despachos

volumes:
  mysql_data:
