name: Deploy Frontend

on:
  push:
    branches:
      - deploy
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Levantar Frontend
        run: |
          echo "Frontend levantado"